apiVersion: v1
kind: Service
metadata:
  labels:
    app: lra-coordinator
    template: lra-coordinator
  name: lra-coordinator
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lra-coordinator
    deploymentconfig: lra-coordinator
  type: ClusterIP